name = "OteraEngine"
uuid = "b2d7f28f-acd6-4007-8b26-bc27716e5513"
authors = ["Momma Watasu"]
version = "0.1.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
